TCDemoProject:
      target: stag_dev # Default target for this profile
      outputs:
        stag_dev:
          type: snowflake
          account: NUDLAMS-FFA15602
          user: bnthierry2
          password: Rwanda@2016
          role: ACCOUNTADMIN
          warehouse: COMPUTE_WH
          database: staging
          schema: bikes

        pres_dev:
          type: snowflake
          account: NUDLAMS-FFA15602
          user: bnthierry2
          password: Rwanda@2016
          role: ACCOUNTADMIN
          warehouse: COMPUTE_WH
          database: presentation
          schema: bikes
      
          #schema: bikes

          #type: [your_data_warehouse_type] # e.g., snowflake, bigquery, postgres
          #database: staging
          #schema: bikes #your_dev_schema_1
          # ... other connection details (user, password, host, etc.)
        stag_prod:
          type: snowflake
          account: NUDLAMS-FFA15602
          user: bnthierry2
          password: Rwanda@2016
          role: ACCOUNTADMIN
          warehouse: COMPUTE_WH
          database: pr_staging
          schema: bikes

        pres_prod:
          type: snowflake
          account: NUDLAMS-FFA15602
          user: bnthierry2
          password: Rwanda@2016
          role: ACCOUNTADMIN
          warehouse: COMPUTE_WH
          database: pr_staging
          schema: bikes

          #type: [your_data_warehouse_type]
          #database: presentation
          #schema: bikes #your_dev_schema_2